-- Additive Migration SQL for Prospects Table
-- Safe and idempotent: Uses ADD COLUMN IF NOT EXISTS so no existing data is deleted or altered.

ALTER TABLE prospects ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS phone VARCHAR(32);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(32);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS whatsapp_source VARCHAR(20);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS website VARCHAR(500);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS city VARCHAR(120);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS locality VARCHAR(120);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS state VARCHAR(120);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS industry VARCHAR(120);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS business_description TEXT;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS company_size_estimate VARCHAR(50);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS source VARCHAR(120);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS google_maps_id VARCHAR(255);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS source_url VARCHAR(1000);
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS social_profiles TEXT;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS google_rating DOUBLE PRECISION;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS review_count INTEGER;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS is_business_active BOOLEAN;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'NEW';
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS verification_status VARCHAR(50) DEFAULT 'UNVERIFIED';
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS last_scraped_at TIMESTAMPTZ;
